application: christopherpenner
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: content/images

- url: /other
  static_dir: content/other

- url: /.*
  script: master.app

libraries:
- name: jinja2
  version: latest
