application: christopherpenner
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: app/assets/css

- url: /js
  static_dir: app/assets/js

- url: /images
  static_dir: content/images

- url: /other
  static_dir: content/other

- url: /.*
  script: app.master.app

libraries:
- name: jinja2
  version: latest
